/**
 * Do not edit directly
 * Generated on Sat, 07 Jun 2025 11:43:14 GMT
 */

export const size-radius-border-xs : number;
export const size-radius-border-s : number;
export const size-radius-border-m : number;
export const size-radius-border-l : number;
export const size-radius-border-circle : number;
export const size-breakpoint-md : number;
export const size-breakpoint-lg : number;
export const size-spacing-zero : number;
export const size-spacing-4-xs : number;
export const size-spacing-3-xs : number;
export const size-spacing-2-xs : number;
export const size-spacing-xs : number;
export const size-spacing-s : number;
export const size-spacing-m : number;
export const size-spacing-l : number;
export const size-spacing-xl : number;
export const size-spacing-2-xl : number;
export const size-spacing-3-xl : number;
export const size-spacing-4-xl : number;
export const size-spacing-5-xl : number;
export const size-line-height-display1 : number;
export const size-line-height-display2 : number;
export const size-line-height-title1 : number;
export const size-line-height-title2 : number;
export const size-line-height-title3 : number;
export const size-line-height-title4 : number;
export const size-line-height-title5 : number;
export const size-line-height-title6 : number;
export const size-line-height-preamble : number;
export const size-line-height-body : number;
export const size-line-height-small : number;
export const size-line-height-link : number;
export const size-line-height-label : number;
export const size-font-display1 : number;
export const size-font-display1-max : number;
export const size-font-display2 : number;
export const size-font-display2-max : number;
export const size-font-title1 : number;
export const size-font-title1-max : number;
export const size-font-title2 : number;
export const size-font-title2-max : number;
export const size-font-title3 : number;
export const size-font-title3-max : number;
export const size-font-title4 : number;
export const size-font-title4-max : number;
export const size-font-title5 : number;
export const size-font-title5-max : number;
export const size-font-title6 : number;
export const size-font-title6-max : number;
export const size-font-preamble : number;
export const size-font-preamble-max : number;
export const size-font-body : number;
export const size-font-body-max : number;
export const size-font-small : number;
export const size-font-small-max : number;
export const size-font-link : number;
export const size-font-link-max : number;
export const size-font-label : number;
export const size-font-label-max : number;
export const colors-brand-primary : "rgb(2, 2, 2)";
export const colors-brand-secondary : "rgb(247, 245, 190)";
export const colors-brand-tertiary : "rgb(109, 191, 184)";
export const colors-link-dark : "rgb(2, 2, 2)";
export const colors-link-medium : "rgb(75, 0, 130)";
export const colors-link-light : "rgb(255, 255, 255)";
export const colors-heading-dark : "rgb(2, 2, 2)";
export const colors-heading-medium : "rgb(109, 191, 184)";
export const colors-heading-light : "rgb(247, 245, 190)";
export const colors-border-primary : "rgb(2, 2, 2)";
export const colors-border-secondary : "rgb(247, 245, 190)";
export const colors-border-tertiary : "rgb(109, 191, 184)";
export const colors-button-dark : "rgb(2, 2, 2)";
export const colors-button-medium : "rgb(247, 245, 190)";
export const colors-button-light : "rgb(255, 255, 255)";
export const colors-semantic-success : "rgb(117, 186, 117)";
export const colors-semantic-success-brighter : "rgb(137, 206, 137)";
export const colors-semantic-warn : "rgb(254, 199, 111)";
export const colors-semantic-info : "rgb(0, 166, 246)";
export const colors-semantic-error : "rgb(178, 34, 34)";
export const colors-dashboard-primary : "rgb(245, 247, 253)";
export const colors-dashboard-secondary : "rgb(78, 80, 132)";
export const colors-dashboard-tertiary : "rgb(255, 255, 255)";
export const shadow-box-s : "0 6px 0 0 rgb(0 0 0 / 1%), 0 15px 32px 0 rgb(0 0 0 / 6%)";
export const shadow-box-m : "2px 10px 30px 0 rgb(0 0 0 / 42%), 0 4px 25px 0 rgb(0 0 0 / 12%)";
export const shadow-box-right-m : "2px 10px 30px -2px rgb(0 0 0 / 42%), 0 4px 25px -5px rgb(0 0 0 / 12%)";
export const typography-display1 : { css: string };
export const typography-display2 : { css: string };
export const typography-title1 : { css: string };
export const typography-title2 : { css: string };
export const typography-title3 : { css: string };
export const typography-title4 : { css: string };
export const typography-title5 : { css: string };
export const typography-title6 : { css: string };
export const typography-preamble : { css: string };
export const typography-body : { css: string };
export const typography-small : { css: string };
export const typography-link-small : { css: string };
export const typography-link : { css: string };
export const typography-label : { css: string };
export const asset-font-typography-light-name : "Roboto, sans-serif";
export const asset-font-typography-light-style : "normal";
export const asset-font-typography-light-weight : "300";
export const asset-font-typography-light-ttf : "assets/Roboto-Light.ttf";
export const asset-font-typography-regular-name : "Roboto, sans-serif";
export const asset-font-typography-regular-style : "normal";
export const asset-font-typography-regular-weight : "400";
export const asset-font-typography-regular-ttf : "assets/Roboto-Regular.ttf";
export const asset-font-typography-bold-name : "Roboto, sans-serif";
export const asset-font-typography-bold-style : "normal";
export const asset-font-typography-bold-weight : "700";
export const asset-font-typography-bold-ttf : "assets/Roboto-Bold.ttf";
export const asset-font-typography-black-name : "Roboto, sans-serif";
export const asset-font-typography-black-style : "normal";
export const asset-font-typography-black-weight : "900";
export const asset-font-typography-black-ttf : "assets/Roboto-Black.ttf";
export const weight-font-display1 : "300";
export const weight-font-display2 : "300";
export const weight-font-title1 : "700";
export const weight-font-title2 : "700";
export const weight-font-title3 : "400";
export const weight-font-title4 : "400";
export const weight-font-title5 : "400";
export const weight-font-title6 : "400";
export const weight-font-preamble : "700";
export const weight-font-body : "400";
export const weight-font-small : "400";
export const weight-font-link : "400";
export const weight-font-label : "400";
